require 'spec_helper'

describe 'Filter, forward:' do
  context 'if .forward is wrongly formatted, an error page will show' do
    before(:each) do
      Filter.unstub(:write_forward)
      Filter.write_forward("test","password","gibberish")
      Filter.unstub(:read_forward)
      login_member('wrong')
    end

    it "shows a message about error in .procmailrc" do
      page.should have_content('Your .forward/.procmailrc was not generated by this system.')
    end
  end
end
